### ISSUE TITLE
支持大佬，希望项目不要烂尾

### ISSUE THREAD

**Issue by Savoir007** [ProbiusOfficial/CTF-OS#1]
打CTF真的需要一个虚拟机系统，在实机装那些软件真的是灾难，
而网上的那些系统都太便离CTF呢 希望大佬坚持住
如果有需要帮忙的 请随时说

**Comment by ProbiusOfficial** [comment]
Beta版本出来了，没咕，故关闭issue（笑

**Comment by Savoir007** [comment]
大佬 牛逼 唯一不足的就是wsl是wsl1有些功能没法使用
不过在大佬基础我修改就行了



在 2024-03-02 19:41:24，"探姬" ***@***.***> 写道：

Beta版本出来了，没咕，故关闭issue（笑

**Comment by ProbiusOfficial** [comment]
哈哈哈哈 也欢迎提供更多的意见以及优化建议~



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2024年3月13日(週三) 下午2:16
收件人： ***@***.***&gt;;
抄送： ***@***.***&gt;;"State ***@***.***&gt;;
主旨： Re: [ProbiusOfficial/CTF-OS] 支持大佬，希望项目不要烂尾 (Issue #1)




 大佬 牛逼 唯一不足的就是wsl是wsl1有些功能没法使用
 不过在大佬基础我修改就行了
 
 
 
 在 2024-03-02 19:41:24，"探姬" ***@***.***&gt; 写道：
 
 Beta版本出来了，没咕，故关闭issue（笑
