### ISSUE TITLE
建议添加sagemath

### ISSUE THREAD

**Issue by wanqian-windrunner** [ProbiusOfficial/CTF-OS#11]
sagemath的win版本已经停止更新了，而且性能不大好，建议使用arch的wsl进行安装，arch里的sagemath一直保持在最新版，还可以加装jupyterlab笔记本。

**Comment by ProbiusOfficial** [comment]
添加sagemath的计划已经列入了下个版本的TODO了。
目前考虑的是在Ubuntu的子系统中添加编译版本的sagemath，不过问了密码的师傅说Ubuntu这边也不能保持最新，如果Arch没问题的话或许会考虑更换或者添加WSL系统。
但是由于没用过Arch，不知道是否会存在稳定性的问题。
我们会争取在下个版本前解决这个问题，如果师傅有更多了解的信息欢迎提供。
