### ISSUE TITLE
给个完整的安装流程呗

### ISSUE THREAD

**Issue by heitongmao** [ProbiusOfficial/CTF-OS#13]
不知道为啥装不到虚拟机上，不是蓝屏就是找不到系统，这个镜像应该搭在哪

**Comment by ProbiusOfficial** [comment]
如果蓝屏 请检查自己虚拟机和系统虚拟平台 虚拟化等配置的具体设置是否冲突。
下载的压缩包解压后就是虚拟机的打包文件，直接导入即可，如有疑问请查阅VM虚拟机官方文档。
