### ISSUE TITLE
建议捏

### ISSUE THREAD

**Issue by Qingjiu233** [ProbiusOfficial/CTF-OS#15]
下个版本能不能往Ubuntu里边装个docker和docker-compose :)
顺手把IDA之类的也塞一塞咩qwq

**Comment by ProbiusOfficial** [comment]
由于 wsl 内核还是进程原因，在虚拟机里给wsl塞docker塞不进去，或许后面还会尝试一下x


二进制环境（re pwn）会在下个版本更新



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2024年3月13日(週三) 上午9:06
收件人： ***@***.***&gt;;
抄送： ***@***.***&gt;;
主旨： [ProbiusOfficial/CTF-OS] 建议捏 (Issue #15)




 
下个版本能不能往Ubuntu里边装个docker和docker-comose :)
 顺手把IDA之类的也塞一塞咩qwq

**Comment by wanqian-windrunner** [comment]
我实体机wsl2的ubuntu可以部署docker，有没有可能是wsl1的问题

**Comment by ProbiusOfficial** [comment]
问题就在这 虚拟机中的docker会基于wsl2安装 但是在虚拟机中的wsl2似乎会出现一些问题导致无法启动？
也可能是我那会弄的时候网络有问题 我这两天再试试



---原始郵件---
寄件人： ***@***.***&gt;
傳送時間： 2024年3月14日(週四) 下午5:16
收件人： ***@***.***&gt;;
抄送： ***@***.******@***.***&gt;;
主旨： Re: [ProbiusOfficial/CTF-OS] 建议捏 (Issue #15)




 
我实体机wsl2的ubuntu可以部署docker，有没有可能是wsl1的问题

**Comment by ProbiusOfficial** [comment]
todo：add docker and docker-compose

**Comment by ProbiusOfficial** [comment]
已完成.
![image](https://github.com/ProbiusOfficial/CTF-OS/assets/41804496/05115dc4-fa24-4f9a-b2b1-05cf122ef722)
