### ISSUE TITLE
VMware导出ovf

### ISSUE THREAD

**Issue by Abyssun** [ProbiusOfficial/CTF-OS#16]
浅浅测了一下，也可能是有电脑本身体质不同导致的，在解压完导入VMware的时候`(这里测试了15、16、17三个版本的VMware)`在15和16两个版本会提示VMware版本较低的报错导致无法正常导入。

**通过导出ovf**后，很明显的在其他版本上也可以直接运行虚拟机，导出ovf后就不需要将整体虚拟机打包成压缩包了，导出后大概会有四个文件，是否有利于虚拟机在网络中传输，还没有验证，目前导出ovf后大概会有15G左右。

**Comment by Abyssun** [comment]
关于虚拟机大小的解决方法，我能想到的是，可以通过在虚拟机的某个位置放一个文档，文档里写着虚拟机原预装工具的下载和快速配置方式`(但好像这样就不方便了)`这样就可以减少最开始下载传输时的大小，由用户下载到本地运行后自行选择下载工具…🤔

**Comment by ProbiusOfficial** [comment]
1.确实 考虑到兼容性问题 使用ovf导出会比直接打包文件好很多（
2.会考虑出两个版本 完全安装和安装包保留版本 —— 但是工作量也会变大，看情况
