### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by allen-x233** [ProbiusOfficial/CTF-OS#18]

**Comment by BoldStart** [comment]
应该还没有上传完哦

**Comment by ProbiusOfficial** [comment]
请保持 OneDrive 账号登陆再访问下载页面.

**Comment by allen-x233** [comment]
![image](https://github.com/ProbiusOfficial/CTF-OS/assets/154351700/a6fe1648-321c-4d3d-96b4-b78aa6117364)依旧有错，没传完？

**Comment by ProbiusOfficial** [comment]
如果在登录状态下依旧无法下载，可能是当前网络节点问题。
请稍等，目前正在建立国内网盘的分流渠道。

**Comment by ProbiusOfficial** [comment]
添加了百度云盘下载地址 链接：https://pan.baidu.com/s/1rvVY79I8sC1TO7dj45p_UQ?pwd=l5bh

**Comment by BoldStart** [comment]
YYDS
