### ISSUE TITLE
有没有办法让win和子系统之间互相访问文件更加便捷呢x

### ISSUE THREAD

**Issue by Qingjiu233** [ProbiusOfficial/CTF-OS#2]
有没有什么办法让win和子系统之间互相访问文件更加便捷呢x
懒狗要哭力）

**Comment by ProbiusOfficial** [comment]
WSL1已经很便捷了呀！
在Win的任意目录右键快捷指令 打开LinuxShell
或者按住 Shift 右键 也有 在此处打开LinuxShell

**Comment by Qingjiu233** [comment]
好的捏 期待更多新手教程（）

**Comment by ProbiusOfficial** [comment]
:p
