### ISSUE TITLE
关闭了虚拟机上的"虚拟化的 Intel VT-x/EPT ",系统里面的子系统都无法打开!

### ISSUE THREAD

**Issue by daymissed** [ProbiusOfficial/CTF-OS#29]
![image](https://github.com/ProbiusOfficial/CTF-OS/assets/62062283/44100436-856f-46a1-9de3-6b12e91b1f2a)

**Comment by daymissed** [comment]
![image](https://github.com/ProbiusOfficial/CTF-OS/assets/62062283/d20cde5f-51f7-43cb-8ea6-35c2ca687893)

**Comment by daymissed** [comment]
启动不了

**Comment by daymissed** [comment]
已搞定.

**Comment by n-WN** [comment]
<img width="1284" alt="image" src="https://github.com/ProbiusOfficial/CTF-OS/assets/30841158/ce470c6d-3aef-4a67-9079-5e832da0166e">

**Comment by n-WN** [comment]
@ProbiusOfficial close

**Comment by gandli** [comment]
[关闭Windows10/11“基于虚拟化的安全性”的四种方法](https://www.bilibili.com/opus/917990899523256320)

方法一：命令行关闭

1、打开终端管理员或cmd。

2、输入bcdedit /set hypervisorlaunchtype off并回车。（若要开启则将off改为auto）


命令生效提示

3、查看选项状态。



方法二：组策略关闭（家庭版系统无效）

1、Win+R运行——输入gpedit.msc并回车 打开组策略。

2、找到“计算机配置——管理模板——系统——Device Guard”右侧的“打开基于虚拟化的安全”策略，将其修改为“已禁用”

3、查看选项状态。



方法三：注册表关闭

1、Win+R运行——输入regedit——回车 打开注册表。

2、找到“HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard”目录右侧的"EnableVirtualizationBasedSecurity"（如果存在，我win11没找到可能是已经关闭的缘故），将其DWORD值修改为0。


参考位置右侧

3、查看选项状态。



如果以上方法都没有用尝试方法四。

方法四：PowerShell脚本关闭（需要win10系统版本1607以上）

1、下载脚本文件并解压缩。链接：https://www.microsoft.com/en-us/download/details.aspx?id=53337


脚本文件如图

2、以管理员模式打开命令行——输入set-ExecutionPolicy RemoteSigned并回车——输入Y并回车


将PowerShell脚本的执行策略更改为运行本地管理员或可信发布者签名的脚本

3、复制刚刚解压缩的脚本路径。


复制自己的，每个人的不一样

4、在管理员模式的命令行中输入cd C:\Users\Administrator\Desktop\dgreadiness_v3.6（命令行右键粘贴）并回车——输入dir并回车查看当前目录内容是否为脚本目录。


命令行

5、输入.\DG_Readiness_Tool_v3.6.ps1 -Disable（注意前面有个点）并回车——等待运行完成后重启电脑——按F3两次，关闭Credential Guard和Device Guard。

6、重启完成后查看选项状态为未启用。
