### ISSUE TITLE
冰蝎报错的解决方法

### ISSUE THREAD

**Issue by ProbiusOfficial** [ProbiusOfficial/CTF-OS#3]
打开冰蝎会提示本地机器上没有找到编译环境，为了正常使用自定义传输协议功能，请使用JDK (而JRE) 环境打开本软件.

原因：java更新时jre-1.8被重置，丢失了tools,jar （当然本来就是自主添加的，这个报错本身应该属于冰蝎自己）

Fix：
复制 C:\Environment\Java\jdk-1.8\lib 的 tools.jar
到 C:\Program Files\Java\jre-1.8\lib 即可.

该项目会尽快引入类似增量更新的方式以优化系统体验.

**Comment by aaaa0323** [comment]
https://r7sn-my.sharepoint.com/:u:/g/personal/pta_r7sn_onmicrosoft_com1/EbegDSGRvgxIgv7pqgPSNVwByoXxJVak4jCZnvWBeFPZVA?e=AxakBP
分流OneDrive下载
