### ISSUE TITLE
导入vm虚拟机

### ISSUE THREAD

**Issue by waiwai24** [ProbiusOfficial/CTF-OS#5]
使用现有虚拟磁盘导入后显示操作系统无法找到，能否给个vmdk的安装教程

**Comment by ProbiusOfficial** [comment]
请参阅 VMware-Workstation-Pro 官方文档 [导入开放式虚拟化格式虚拟机](https://docs.vmware.com/cn/VMware-Workstation-Pro/17/com.vmware.ws.using.doc/GUID-DDCBE9C0-0EC9-4D09-8042-18436DA62F7A.html)

**Comment by waiwai24** [comment]
谢谢，我一开始以为是解压问题，一直没有找到.ovf文件。
最简单的导入办法是：
1. 点击左上角文件
2. 选择扫描虚拟机
3. 选择压缩包的位置
4. 自动识别后可直接导入
