### ISSUE TITLE
磁盘扩容

### ISSUE THREAD

**Issue by waiwai24** [ProbiusOfficial/CTF-OS#7]
- 点击虚拟机设置
- 点击硬件选项的左下角添加
- 选择添加硬盘即可
- 打开虚拟机中的磁盘管理
- 点击新建卷即可

**Comment by ProbiusOfficial** [comment]
如果需要扩展主磁盘（C），可以使用内置的分区助手。
添加磁盘使用自带磁盘管理或者其他分区软件均可，但请注意备份数据。
