### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by Lucke9** [ProbiusOfficial/CTF-OS#8]
今天试用了一下，希望能把git 加入到环境里边，想添加东西的时候会方便些

**Comment by ProbiusOfficial** [comment]
会在下次发版时更新~

**Comment by Answerr** [comment]
没有IDA吗

**Comment by ProbiusOfficial** [comment]
git 已在WSL子系统中集成，可与Windows文件系统直接交互。
此外推荐在Linux中运行git，避免遇到win/linux文件系统差异导致的问题，另外，如果考虑网络问题，可以使用 export 命令去指向宿主机代理。
暂时不考虑在宿主机(Windows)上添加Git
