### ISSUE TITLE
系统登入密码是多少啊

### ISSUE THREAD

**Issue by qjj5933** [ProbiusOfficial/CTF-OS#9]
刚刚安装好系统，就是不知道登入密码是多少

**Comment by D2550** [comment]
Windows Password: hello-ctf.com
Ubuntu Password: ctfos

**Comment by ProbiusOfficial** [comment]
请仔细阅读Releases中的系统说明.
Windows Password: `hello-ctf.com`
Ubuntu Password: `ctfos`
